# @name createKycRegulatoryScope
### Create a RegulatoryScope for KYC Onboarding (CNI, Passport, Proof of Address)
POST {{apiUrl}}/regulatory-scopes
Content-Type: application/ld+json
Accept: application/ld+json

{
  "code": "KYC_VERIFICATION",
  "label": "Vérification d'identité KYC",
  "description": "Périmètre de conformité pour la vérification d'identité des clients (CNI, Passeport, Justificatif de domicile)",
  "allowedDocumentTypes": ["CNI", "PASSPORT", "JUSTIFICATIF_DOMICILE"],
  "isActive": true
}

###

# @name listRegulatoryScopes
### List RegulatoryScopes
GET {{apiUrl}}/regulatory-scopes
Accept: application/ld+json

###

# @name getKycRegulatoryScopeByCode
### Get a RegulatoryScope by code (KYC_VERIFICATION)
GET {{apiUrl}}/regulatory-scopes/KYC_VERIFICATION
Accept: application/ld+json

###

# @name getUnknownRegulatoryScope
### Get an unknown RegulatoryScope
GET {{apiUrl}}/regulatory-scopes/DOES_NOT_EXIST
Accept: application/ld+json
