# @name checkSystemStatus
### Check System Status (Health Check V1)
GET {{apiUrl}}/health
Accept: application/ld+json

###

# @name checkOpenApiSpec
### Check OpenApi Json Specification
GET {{baseUrl}}/api/docs.json
Accept: application/json
